# Version of docker compose syntax we are going to be using
version: "3.9"

# name is app
# build context the . means current directory or root
# ports maps the port 8000 from local to 8000 in container
# volumes map the directory from system to container
# this lets updates be made in the container
# command that is used to run the service
# has to be specified so it uses this command if we do not specify when running
#
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"